# fly.toml app configuration file generated for auto-vpn on 2024-11-30T08:42:26-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'auto-vpn'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = "512mb"
  swap_size_mb = 1024 
