name: Trigger Render Redeploy

on:
  workflow_run:
    workflows: ["Docker Build and Publish"]
    types:
      - completed

jobs:
  redeploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Send redeploy request to Render
        run: |
          curl -X POST -H "Accept: application/json" ${{ secrets.RENDER_DEPLOY_URL }}

